production:
    dialect: mysql
    datasource: root@/dbname?parseTime=true
    dir: migrations/mysql
    table: migrations
development:
    dialect: mysql
    datasource: test.db
    dir: migrations/mysql
    table: migrations
    datasource: root@/dbname?parseTime=true
